Prettify message input
codeu-su-19-team-43/team-43-codeu pull request #110
Opened 2019-07-16 14:33 UTC by anqitu

2019-07-16 14:46 UTC, amad-person commented
Is this expected? Shouldn't the input area be separate from the gallery?

<img width="798" alt="Screenshot 2019-07-16 at 10 45 10 PM" src="https://user-images.githubusercontent.com/22164211/61304217-6692f080-a81b-11e9-8076-472c899f9bda.png">

2019-07-16 14:47 UTC, amad-person requested changes
Position of message input, just confirming whether it is being changed

2019-07-17 14:30 UTC, anqitu commented
New UI
![image](https://user-images.githubusercontent.com/23692850/61384073-6f9ac500-a8e2-11e9-8ef1-3c597f45564b.png)
![image](https://user-images.githubusercontent.com/23692850/61384080-7590a600-a8e2-11e9-8989-ea3cecc47fae.png)

2019-07-18 11:52 UTC, amad-person approved these changes

2019-07-18 11:52 UTC, merged